class inference:
    def __init__(self):
        pass

    def inference(self,chest_pain,blood_pressure,cholesterol,blood_sugar,ECG,maximum_heart_rate,exercise,old_peak,thallium,sex,age):
       output_sick1,output_sick2,output_sick3,output_sick4,output_healthy = ([] for i in range(5))
       # 54 rules defined here ...
       output_sick4.append(min(age['very_old'],chest_pain['atypical_anginal']))
       output_sick4.append(min(maximum_heart_rate['high'],age['old']))
       output_sick3.append(min(sex['male'],maximum_heart_rate['medium']))
       output_sick2.append(min(sex['female'],maximum_heart_rate['medium']))
       output_sick3.append(min(chest_pain['non_aginal_pain'],blood_pressure['high']))
       output_sick2.append(min(chest_pain['typical_anginal'],maximum_heart_rate['medium']))
       output_sick3.append(min(blood_sugar['true'],age['mild']))
       output_sick2.append(min(blood_sugar['false'],blood_pressure['very_high']))
       output_sick1.append(max(chest_pain['asymptomatic'],age['very_old']))
       output_sick1.append(max(blood_pressure['high'],maximum_heart_rate['low']))
       output_healthy.append(chest_pain['typical_anginal'])
       output_sick1.append(chest_pain['atypical_anginal'])
       output_sick2.append(chest_pain['non_aginal_pain'])
       output_sick3.append(chest_pain['asymptomatic'])
       output_sick4.append(chest_pain['asymptomatic'])
       output_sick1.append(sex['female'])
       output_sick2.append(sex['male'])
       output_healthy.append(blood_pressure['low'])
       output_sick1.append(blood_pressure['medium'])
       output_sick2.append(blood_pressure['high'])
       output_sick3.append(blood_pressure['high'])
       output_sick4.append(blood_pressure['very_high'])
       output_healthy.append(cholesterol['low'])
       output_sick1.append(cholesterol['medium'])
       output_sick2.append(cholesterol['high'])
       output_sick3.append(cholesterol['high'])
       output_sick4.append(cholesterol['very_high'])
       output_sick2.append(blood_sugar['true'])
       output_healthy.append(ECG['normal'])
       output_sick1.append(ECG['normal'])
       output_sick2.append(ECG['abnormal'])
       output_sick3.append(ECG['hypertrophy'])
       output_sick4.append(ECG['hypertrophy'])
       output_healthy.append(maximum_heart_rate['low'])
       output_sick1.append(maximum_heart_rate['medium'])
       output_sick2.append(maximum_heart_rate['medium'])
       output_sick3.append(maximum_heart_rate['high'])
       output_sick4.append(maximum_heart_rate['high'])
       output_sick2.append(exercise['true'])
       output_healthy.append(old_peak['low'])
       output_sick1.append(old_peak['low'])
       output_sick2.append(old_peak['terrible'])
       output_sick3.append(old_peak['terrible'])
       output_sick4.append(old_peak['risk'])
       output_healthy.append(thallium['normal'])
       output_sick1.append(thallium['normal'])
       output_sick2.append(thallium['medium'])
       output_sick3.append(thallium['high'])
       output_sick4.append(thallium['high'])
       output_healthy.append(age['young'])
       output_sick1.append(age['mild'])
       output_sick2.append(age['old'])
       output_sick3.append(age['old'])
       output_sick4.append(age['very_old'])
       return dict(
            outputsick_sick1=max(output_sick1),
            outputsick_sick2=max(output_sick2),
            outputsick_sick3=max(output_sick3),
            outputsick_sick4=max(output_sick4),
            outputsick_healthy=max(output_healthy)
        )
